# Generated by Django 4.2.4 on 2023-12-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='option3',
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='vote.candidate'),
        ),
    ]
